services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    env_file:
      - website/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - certnet
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: certdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - certnet

networks:
  certnet:
    driver: bridge

volumes:
  mysql_data:
    name: mysql_data